apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: project1-project1-poi-map-app-dev
  annotations:
    argocd/app-name: project1-project1-poi-map-app-dev
    backstage.io/kubernetes-id: project1-project1-poi-map-app-dev
    backstage.io/kubernetes-namespace: project1
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=project1-project1-poi-map-app-dev'
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: Summit23Janus2/project1-frontend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - typescript
    - angular
    - workshop
  links:
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/dev-pipelines/ns/project1/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.summit23blues.6mbu.p1.openshiftapps.com/k8s/ns/project1/deployments/project1-poi-map-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.summit23blues.6mbu.p1.openshiftapps.com/#https://github.com/Summit23Janus2/project1-frontend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: http://project1-poi-map-app-project1.apps.summit23blues.6mbu.p1.openshiftapps.com
      title: Map
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/theitrx"
  system: workshop-system-project1
  consumesApis:
    - gateway-api-project1
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-project1
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/theitrx"
